- robotpy_build/platforms.py
- robotpy_build/wrapper.py
Adds the ability to copy multiple file types over using a pipe as a extension separator.
Ex: `WPILibMavenPlatform("windows", "x86-64", "", ".dll|.lib")`
Removes the issue where the .lib files from the win-x32-64 artifacts would not be loaded and usable, while preserving functionality for any os that doesn't require multiple files.
> Add support for multiple .lib or .dll files

- robotpy_build/pyproject_configs.py
- robotpy_build/wrapper.py
`dll` files are required in windows libraries. However, `lib` files are only with some `dll`s.
This adds optional link extensions and adds an `optional` parameter in the download functions.
This patch allows halsim to build on Windows.
> Fix Windows Library Linking

- robotpy_build/pyproject_configs.py
- robotpy_build/setup.py
This package's own python_requires is fixed in #32.
> Fix python_requires typo

- robotpy_build/pyproject_configs.py
- robotpy_build/setup.py
- robotpy_build/wrapper.py
Example config in pyproject.toml:
```toml
[tool.robotpy-build]
base_package = "rev"
unsupported_platforms = [
{ os = "osx" },
{ os = "windows", arch = "x86" }
]
```
Example error messages:
{ os = "osx" }:
"OSError: robotpy-rev is not supported on macOS!"
{ os = "windows", arch = "x86" }:
"OSError: robotpy-rev is not supported on 32-bit windows!"
{ arch = "x86" }:
"OSError: robotpy-rev is not supported on 32-bit versions of Python!"
> Add helpful error if a user tries to install an rpy package on an Unsupported Platform

- robotpy_build/tool.py
The tool finds `maven_lib_downloads` in a given pyproject.toml and finds supported platforms by scraping html. A brute force option is given when html is not available (rev).
Ex. 
```bash
robotpy-build parse-maven pyproject.toml
```
Output:
```bash
Wrapper / static_lib :: hal
Artifact ID :: hal-cpp
This repo appears to provide sources.
The name of the source file is: sources
supported_platforms = [
{ os = "linux", arch = "raspbian" },
{ os = "linux", arch = "aarch64bionic" },
{ os = "linux", arch = "x86-64" },
{ os = "linux", arch = "athena" },
{ os = "osx", arch = "x86-64" },
{ os = "windows", arch = "x86" },
{ os = "windows", arch = "x86-64" },
]
```
> Add tool to detect supported platforms

- robotpy_build/pkgcfg_provider.py
- robotpy_build/setup.py
closes #47.
The `error: [WinError 183] Cannot create a file when that file already exists: 'C:\\...\\command2\\lib' ` error occurs on consecutive builds because rpy-build still has a file handle open on the lib folder. This handle is opened in `PkgCfgProvider` and never closed. PkgCfgProvider loads all robotpybuild modules it finds, including the module it's currently building.
This PR changes PkgCfgProvider so it only loads modules that the current module depends on.
> Only load packages that are dependencies

- robotpy_build/templates/cls.cpp.j2
- robotpy_build/templates/cls_tmpl_impl.hpp.j2
- robotpy_build/templates/pybind11.cpp.j2
- robotpy_build/wrapper.py
- tests/cpp/gen/ft/tbasic.yml
- tests/cpp/gen/ft/tdependent_using.yml
- tests/cpp/pyproject.toml.tmpl
- tests/cpp/rpytest/ft/__init__.py
- tests/cpp/rpytest/ft/include/templates/dependent_using.h
- tests/test_ft_templates.py
- Use a two-phase registration so that all objects are registered before trying to use them
- Fixes #43
> Fix circular dependencies in object registration

- examples/demo/.gitignore
- robotpy_build/command/build_ext.py
- robotpy_build/command/build_pyi.py
- robotpy_build/relink_libs.py
- robotpy_build/setup.py
- setup.cfg
- tests/cpp/.gitignore
- tests/cpp/rpytest/ft/include/inheritance/ibase.h
- Fixes #1
... I haven't really tried this yet with anything other than the demo, so YMMV.
> Automatically generate pyi stubs for built extensions

- robotpy_build/setup.py
`twine check` warns about the missing content type.
> Squash long description content type warning

- robotpy_build/command/build_ext.py
- robotpy_build/generator_data.py
- robotpy_build/hooks_datacfg.py
- robotpy_build/templates/cls.cpp.j2
- robotpy_build/templates/cls_trampoline.hpp.j2
- robotpy_build/templates/pybind11.cpp.j2
- tests/cpp/gen/ft/docstrings_append.yml
- tests/cpp/gen/ft/ignore.yml
- tests/cpp/gen/ft/rename.yml
- tests/cpp/gen/ft/subpkg.yml
- tests/cpp/gen/ft/tbase.yml
- tests/cpp/gen/ft/tbasic.yml
- tests/cpp/gen/ft/tconcrete.yml
- tests/cpp/gen/ft/tcrtp.yml
- tests/cpp/gen/ft/tcrtpfwd.yml
- tests/cpp/gen/ft/tdependent_param.yml
- tests/cpp/gen/ft/tdependent_using.yml
- tests/cpp/gen/ft/tfn.yml
- tests/cpp/gen/ft/tnested.yml
- tests/cpp/gen/ft/tnumeric.yml
- tests/cpp/gen/ft/virtual_xform.yml
- No longer need to include 'shared_ptr: true', as this is automatic now
I think this won't work for something that is templated and marked as nodelete. Need to add a test to check.
> Use the pybind11 smart_holder branch

- robotpy_build/templates/cls.cpp.j2
- robotpy_build/templates/cls_tmpl_impl.hpp.j2
- robotpy_build/templates/pybind11.cpp.j2
- Fixes issue with a method that had another class' enum value as a default argument
- Not going to write a test for this since it seems a bit random
> Set enum values in the initialization stage since they can't have dependencies

- .github/workflows/dist.yml
- robotpy_build/hooks.py
- robotpy_build/hooks_datacfg.py
- robotpy_build/mangle.py
- robotpy_build/templates/cls.cpp.j2
- robotpy_build/templates/cls_trampoline.hpp.j2
- robotpy_build/templates/pybind11.cpp.j2
- setup.cfg
- tests/cpp/gen/ft/refqual.yml
- tests/cpp/pyproject.toml.tmpl
- tests/cpp/rpytest/ft/include/refqual.h
- tests/test_ft_refquals.py
- Correctly add & and && to trampoline definitions and function casts
- Provide ignore_py and trampoline_cpp_code
> Add features to properly support methods with ref-qualifiers

- robotpy_build/platforms.py
Platforms like my ODROID-XU4 come in as "linux-armv7l". Treating this as plain "arm32", with no special DEFINE like for RPi, seems to work for me.
> Add linux-armv7l as plain 32-bit ARM

- robotpy_build/platforms.py
This wheel fails to build on Apple Silicon (M1, M2, &c). This branch provides for it.
Not sure about provisioning arm64 test runners in the GitHub workflows.
> Provide for Apple Silicon (ARM64) platform as well

- robotpy_build/command/build_dl.py
Fixes issue reported by @auscompgeek ... any thoughts on a better way to do this?
Tested on a roborio cross compile.
> Strip linux binaries correctly when cross-compiling

- .github/workflows/dist.yml
- tests/requirements.txt
- Use trusted publishing
- Build wheel once and reuse it
> Update github actions

- robotpy_build/autowrap/cxxparser.py
- tests/cpp/rpytest/ft/include/overloads.h
- Still need to track whether they're an overload or not, otherwise we run into ambiguity
> Do minimal processing of ignored functions

- robotpy_build/autowrap/cxxparser.py
- robotpy_build/autowrap/header.cpp.j2
- robotpy_build/autowrap/j2_context.py
- tests/cpp/gen/ft/tdependent_base.yml
- tests/cpp/pyproject.toml.tmpl
- tests/cpp/rpytest/ft/include/templates/dependent_base.h
- If it depends on a base class, the base needs to be initialized first
- Not all template classes exist in the header (in particular, CRTP) so anything not found in the current header gets initialized first
> Ensure template classes are instantiated in correct order

- .github/workflows/dist.yml
- pyproject.toml
- setup.cfg
<details>
<summary>Changes since 2.3.x</summary>
Version 2.5.1 (Mar 26, 2024)
--------------------------
Changes:
- 🐛 Fixed: Missed numpy unsigned int types
Version 2.5 (Mar 3, 2024)
--------------------------
Changes:
- 🐛 Fixed: Don't render pybind11 `KeysView`, `ValuesView`, `ItemsView` class definitions
- 🐛 Fixed: Escape backslashes in stub output
Version 2.4.1 (Nov 25, 2023)
--------------------------
Changes:
- 🐛 Fixed: do not remove `self` parameter annotation when types do not match
Version 2.4 (Nov 21, 2023)
--------------------------
Changes:
- ✨ Added `--numpy-array-use-type-var` flag which reformats the pybind11-generated `numpy.ndarray[numpy.float32[m, 1]]` annotation as `numpy.ndarray[tuple[M, Literal[1]], numpy.dtype[numpy.float32]]`
</details>
> Update pybind11-stubgen to 2.5.x

- robotpy_build/autowrap/context.py
- robotpy_build/autowrap/cxxparser.py
- robotpy_build/autowrap/render_cls_rpy_include.py
- tests/cpp/pyproject.toml.tmpl
- tests/cpp/rpytest/ft/include/ns_hidden.h
- This simplifies wrapping somewhat and avoids compile errors when the trampoline references a class in a parent namespace
- This is a breaking change -- bindings need to be recompiled to match each other
> Put trampolines in original class namespace

- robotpy_build/autowrap/cxxparser.py
- robotpy_build/autowrap/render_pybind11.py
- robotpy_build/config/autowrap_yml.py
- tests/cpp/gen/ft/rename.yml
- tests/cpp/rpytest/ft/include/rename.h
- tests/test_ft_rename.py
Occasionally we want to expose a C++ constructor overload as a static method rather than an overload.
> Allow renaming constructor overloads to static methods

- robotpy_build/autowrap/cxxparser.py
Sometimes we don't actually need keepalives for references passed to constructors. For example, none of [Rotation3d]'s const-ref-taking constructor overloads hold the references in the instance.
Allow an explicit empty list to disable the constructor reference keepalive inference.
[Rotation3d]: https://github.com/wpilibsuite/allwpilib/blob/d4985b8ba062eec75f76dd8e40acb1282d2dc6c4/wpimath/src/main/native/include/frc/geometry/Rotation3d.h#L41
> Allow disabling keepalive inference for constructors

- robotpy_build/command/build_ext.py
setuptools v72.2.0 added realer support for C++, which includes understanding the C++ compiler usually has a different name.
https://github.com/pypa/setuptools/commit/2c937116cc0dcd9b26b6070e89a3dc5dcbedc2ae
> build_ext: Support C++ for RPYBUILD_CC_LAUNCHER

- robotpy_build/autowrap/render_pybind11.py
- robotpy_build/command/build_ext.py
- tests/test_ft_docs.py
- This is a breaking change, but it's worth it, and nobody uses robotpy-build anyways
> Upgrade to pybind11 v3 prerelease

- robotpy_build/include/robotpy_build.h
- tests/cpp/rpytest/ft/__init__.py
- tests/cpp/rpytest/ft/src/ft.cpp
- tests/test_ft_misc.py
- This has been included in pybind11 for awhile now
> Remove rpybuild_ext::raise_from

- .github/workflows/dist.yml
The aarch64 cross-build image is no longer used downstream.
> ci: Remove aarch64 cross-build

- robotpy_build/wrapper.py
If multiple downloads are specified in the pyproject.yaml (e.g. [[tool.robotpy-build.wrappers."<package name>".download]] is repeated), the first one will create the lib directory where the download's libraries will be extracted to. However, the second will fail because the lib directory already exists. I just modified this to add exist_ok to the os.makedirs call so the second (and third, etc.) can add their libraries as well.
> Multiple Dependency Libraries
